### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by UriHerrera** [plasma-light/plasma-widget-radio#1]
I've use used the following description:

> Plasmoid to listen to online radio stations.

@star-buck mentioned that this plasmoid was to be used on the system tray too like `plasmoid-widget-spectacle`.

I also think that it can work too as a widget on the desktop itself similarly like Covergloobus, the all familiar media playing widget.

When placed on the system tray it'd show a menu window with multimedia controls for quick access and when placed on the desktop it'd show more UI elements, like a media seeker, timer and/or a playlist with stations.

cc @azubieta

**Comment by star-buck** [comment]
Here is the link to an old gtk2 version:
http://radiotray.sourceforge.net/

Since its mainly python, maybe we can simply add Qt frontend? :)

**Comment by azubieta** [comment]
Let's see, if the code for fetching the radio stream is separated from the glib/gtk2 it should be straigforward.
Or not, the python support in kde5 is quite inmature, please check this out https://forum.kde.org/viewtopic.php?f=289&t=124308

**Comment by azubieta** [comment]
As an alternative we can make of it a background dbus service, and controll it from the widget or look for an application that already provide such service.

**Comment by UriHerrera** [comment]
I made a mockup:

![](http://i.imgur.com/8KQPvrE.png)
![](http://i.imgur.com/hPQejSr.png)

Overall I kept the design we used for the Spectacle plasmoid. The shuffle icon would shuffle between stations from a given genre. The previous and next buttons would change stations within the current genre. The playlist icon would show the genres available from which the plasmoid would fetch the streams.

It would show the name of the station and the bit rate along with the logo of the station or if possible the artwork of the song.

**Comment by azubieta** [comment]
It looks pretty good!
Would you please make one for the playlist management too.

**Comment by UriHerrera** [comment]
![](http://i.imgur.com/RalGvD9.png)

I'm thinking of adding new stations in the settings to keep the plasmoid interface clean like this and the other mockup. The list would show the stations added the "playlist" and their bit rate. The current station has a play symbol next to it.

**Comment by NuLogicSystems** [comment]
A stop button would be nice. As it is now you can only pause the live stream, which will be out of sync when you resume the stream. You then have to hit forward and back, or vice versa, to back in sync with the live stream.

**Comment by azubieta** [comment]
Well, I think that that would be a better behavior for the pause, because we would like to be always in sync.
