### ISSUE TITLE
About the backend

### ISSUE THREAD

**Issue by azubieta** [plasma-light/plasma-widget-radio#2]
I have been exploring the different alternatives that have to implement the widget backend and here are the results:
Separated process approach:
- CLI INTERFACE: vlc, ffmpg, mocp, mpc or another existent music player
- DBUS INTERFACE: also vlc, and the other existent music players, also we can make our own (but it isn't recommended)

Integrated approach:
- Qt-Gstreamer, works well with local files, but it just crashes on remote sources
- lib-vlc-qt, still can't make it work on my opensuse

I would like to hear your toughts, the first is the easiest way but we will have an extra dependency, the others are a little bit tricky. I trying to make the examples that they provide work on my system without any look yet.

**Comment by UriHerrera** [comment]
I vote for using  vlc-cli. VLC is much more likely to be used by users already than the other alternatives. And it would be easier for the plasmoid's creation.

**Comment by star-buck** [comment]
How does radiotray work?

**Comment by azubieta** [comment]
@star-buck well it compiles and runs but I was unable to test it because i'm behind a proxy and it doesn't support it. Also there is no support in KDE5 to python plugins it is incrusted on the tray using the legacy X11 tray. In order to use it's code we must adapt it to run as a separated service and control it via dbus.

But there are good news, after a while, I managed to make libvlc work so there will be no need to do all the above and the widget will code will be much simpler.
