### ISSUE TITLE
rc this month

### ISSUE THREAD

**Issue by star-buck** [plasma-light/plasma-widget-radio#3]
Any update on this?

**Comment by UriHerrera** [comment]
There's a new branch to try out. Though you're going to have to test it on openSUSE because the library libvlc-qt has different names on other distributions. I'm modding the files to run it on Manjaro.

**Comment by star-buck** [comment]
The distros supported by Blue Systems are Debian and KUbuntu/Neon, so packages for those would be best. Manjaro is more like a secondary effort.

**Comment by UriHerrera** [comment]
I've checked out the [libvlc-qt package for Ubuntu](https://launchpad.net/~ntadej/+archive/ubuntu/tano) at the PPA set up by the developer and it uses the same library names as Manjaro so it will work :D

For example: openSUSE uses `libvlc-qt.so` but both the PPA package and the AUR package output `libVLCQtCore.so`. No idea why openSUSE would change it.

**Comment by azubieta** [comment]
I have reduced the dependencies list only to libvlc (libvlc-qt was removed) and test it with the sources from github, so there should not be problem on building it for debian or Kubunut.
