### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by azubieta** [plasma-light/plasma-widget-radio#6]
Create the icons for:
- systemtray
- playmode "secuential play"

**Comment by UriHerrera** [comment]
Agregue los dos iconos a `development`. El de la bandeja es `radio-tray` y el otro es `media-player-continuous`

**Comment by azubieta** [comment]
I didn't found the icon "media-player-continuous" in my system and in the images folder it's only the "radio-tray" icon.

**Comment by UriHerrera** [comment]
https://github.com/plasma-light/plasma-widget-radio/commit/2a6d2e967cdc7620b3e5f18b745f50e1e156e761

No se que pasa con la aplicacion de Github para Windows.
