### ISSUE TITLE
plasma-widget-radiotray fails to build

### ISSUE THREAD

**Issue by shadeslayer** [plasma-light/plasma-widget-radio#7]
http://dci.pangea.pub/job/stable_stable_ds9-debian-packaging_plasma-widget-radiotray_bin_amd64/3/console

**Comment by azubieta** [comment]
Are these parameters set in the cmake config ?
-DCMAKE_INSTALL_PREFIX=`kde4-config --prefix` -DCMAKE_BUILD_TYPE=Release -DLIB_INSTALL_DIR=lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON

**Comment by Fisiu** [comment]
Current version requires vlc from git, at least: https://github.com/videolan/vlc/commit/688e3bcb4d05b8e3274b7e17aec90a70ac44d960.
